version: "3.7"
services:

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ${PWD}/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}:/app:cached
    ports:
      - 8080:80
    working_dir: /app

  php:
    build: ${PWD}/docker
    restart: always
    volumes:
      - ${PWD}/docker/php/app.ini:/usr/local/etc/php/conf.d/zzz-app.ini
      - ${PWD}:/app:cached
    working_dir: /app

  database:
    image: mariadb:10
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--explicit_defaults_for_timestamp"
      - "--sql_mode="
    restart: always
    volumes:
      - ${PWD}/docker/mariadb/entrypoint:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  # memcached:
  #   image: memcached:alpine
  #   restart: always

volumes:
  dbdata:
